class PlantProfile {
  final String nombre;
  final String emoji;
  final double tempMin, tempMax;
  final double phMin, phMax;
  final double ecMin, ecMax;
  final double nivelAguaMin;
  final double nivelFertilizanteMin;
  // ── Cultivo en tierra (soil-first, ROADMAP_PRODUCTO.md P1) ─────────────────
  // Opcionales: null en perfiles hidropónicos, que no miden humedad de suelo.
  final double? humedadSueloMin; // % — umbral bajo de humedad de suelo
  final double? humedadSueloMax; // % — umbral alto (opcional)
  final String tipoCultivo; // 'suelo' | 'hidroponico'
  final String fuente;

  const PlantProfile({
    required this.nombre,
    required this.emoji,
    required this.tempMin,
    required this.tempMax,
    required this.phMin,
    required this.phMax,
    required this.ecMin,
    required this.ecMax,
    required this.nivelAguaMin,
    required this.nivelFertilizanteMin,
    this.humedadSueloMin,
    this.humedadSueloMax,
    this.tipoCultivo = 'hidroponico',
    required this.fuente,
  });

  factory PlantProfile.fromMap(Map<dynamic, dynamic> map) {
    return PlantProfile(
      nombre: map['planta'] as String? ?? '',
      emoji: map['emoji'] as String? ?? '🌱',
      tempMin: (map['temp_min'] as num?)?.toDouble() ?? 0.0,
      tempMax: (map['temp_max'] as num?)?.toDouble() ?? 0.0,
      phMin: (map['ph_min'] as num?)?.toDouble() ?? 0.0,
      phMax: (map['ph_max'] as num?)?.toDouble() ?? 0.0,
      ecMin: (map['ec_min'] as num?)?.toDouble() ?? 0.0,
      ecMax: (map['ec_max'] as num?)?.toDouble() ?? 0.0,
      nivelAguaMin: (map['nivel_agua_min'] as num?)?.toDouble() ?? 20.0,
      nivelFertilizanteMin:
          (map['nivel_fertilizante_min'] as num?)?.toDouble() ?? 20.0,
      humedadSueloMin: (map['humedad_suelo_min'] as num?)?.toDouble(),
      humedadSueloMax: (map['humedad_suelo_max'] as num?)?.toDouble(),
      tipoCultivo: map['tipo_cultivo'] as String? ?? 'hidroponico',
      fuente: map['fuente'] as String? ?? '',
    );
  }

  Map<String, dynamic> toMap() => {
    'planta': nombre,
    'emoji': emoji,
    'temp_min': tempMin,
    'temp_max': tempMax,
    'ph_min': phMin,
    'ph_max': phMax,
    'ec_min': ecMin,
    'ec_max': ecMax,
    'nivel_agua_min': nivelAguaMin,
    'nivel_fertilizante_min': nivelFertilizanteMin,
    'humedad_suelo_min': humedadSueloMin,
    'humedad_suelo_max': humedadSueloMax,
    'tipo_cultivo': tipoCultivo,
    'fuente': fuente,
  };
}

class PlantCatalog {
  static const List<PlantProfile> plantas = [
    // ═══════════════════════════════════════════════════════════════════
    // HORTALIZAS HIDROPÓNICAS
    // ═══════════════════════════════════════════════════════════════════
    PlantProfile(
      nombre: 'Tomate Cherry',
      emoji: '🍅',
      tempMin: 18, tempMax: 28,
      phMin: 5.5, phMax: 6.5,
      ecMin: 2.0, ecMax: 3.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Al-Gaadi et al. (2024), Phyton 93(6)',
    ),
    PlantProfile(
      nombre: 'Tomate de Árbol',
      emoji: '🍅',
      tempMin: 14, tempMax: 22,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.5, ecMax: 2.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'CORPOICA / Agronet Colombia',
    ),
    PlantProfile(
      nombre: 'Lechuga Romana',
      emoji: '🥬',
      tempMin: 15, tempMax: 22,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.0, ecMax: 1.8,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Rofiansyah et al. (2025), PeerJ CS',
    ),
    PlantProfile(
      nombre: 'Lechuga Crespa',
      emoji: '🥬',
      tempMin: 14, tempMax: 22,
      phMin: 5.5, phMax: 6.5,
      ecMin: 0.8, ecMax: 1.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Howard Resh, Hydroponic Food Production (2022)',
    ),
    PlantProfile(
      nombre: 'Espinaca',
      emoji: '🥬',
      tempMin: 12, tempMax: 22,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.5, ecMax: 2.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Resh (2022), Hydroponic Food Production',
    ),
    PlantProfile(
      nombre: 'Acelga',
      emoji: '🥬',
      tempMin: 14, tempMax: 24,
      phMin: 6.0, phMax: 7.0,
      ecMin: 1.5, ecMax: 2.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'FAO, Manual de hidroponía simplificada',
    ),
    PlantProfile(
      nombre: 'Rúgula / Rúcula',
      emoji: '🥗',
      tempMin: 15, tempMax: 22,
      phMin: 6.0, phMax: 7.0,
      ecMin: 0.8, ecMax: 1.4,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Resh (2022), Hydroponic Food Production',
    ),
    PlantProfile(
      nombre: 'Pepino',
      emoji: '🥒',
      tempMin: 20, tempMax: 30,
      phMin: 5.5, phMax: 6.0,
      ecMin: 1.7, ecMax: 2.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Resh (2022), Hydroponic Food Production',
    ),
    PlantProfile(
      nombre: 'Pimiento',
      emoji: '🫑',
      tempMin: 20, tempMax: 30,
      phMin: 5.8, phMax: 6.5,
      ecMin: 1.8, ecMax: 2.8,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Rahman et al. (2023), Eur. J. Appl. Sci.',
    ),
    PlantProfile(
      nombre: 'Ají Tabasco',
      emoji: '🌶️',
      tempMin: 20, tempMax: 32,
      phMin: 5.5, phMax: 6.5,
      ecMin: 2.0, ecMax: 3.0,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'CORPOICA; Resh (2022)',
    ),
    PlantProfile(
      nombre: 'Ají Habanero',
      emoji: '🌶️',
      tempMin: 22, tempMax: 34,
      phMin: 5.5, phMax: 6.5,
      ecMin: 2.0, ecMax: 3.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'CORPOICA; parámetros tropicales',
    ),
    PlantProfile(
      nombre: 'Fresa',
      emoji: '🍓',
      tempMin: 15, tempMax: 25,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.0, ecMax: 1.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Resh (2022), Hydroponic Food Production',
    ),
    PlantProfile(
      nombre: 'Uchuva / Physalis',
      emoji: '🟡',
      tempMin: 13, tempMax: 22,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.2, ecMax: 2.0,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'CORPOICA / Agronet Colombia',
    ),
    PlantProfile(
      nombre: 'Lulo / Naranjilla',
      emoji: '🟠',
      tempMin: 16, tempMax: 24,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.5, ecMax: 2.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'CORPOICA; Agrosavia Colombia',
    ),
    PlantProfile(
      nombre: 'Rábano',
      emoji: '🟥',
      tempMin: 15, tempMax: 22,
      phMin: 6.0, phMax: 7.0,
      ecMin: 1.0, ecMax: 1.8,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Resh (2022), Hydroponic Food Production',
    ),
    PlantProfile(
      nombre: 'Zanahoria Baby',
      emoji: '🥕',
      tempMin: 16, tempMax: 24,
      phMin: 6.0, phMax: 6.8,
      ecMin: 1.5, ecMax: 2.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'FAO; Resh (2022)',
    ),
    PlantProfile(
      nombre: 'Apio',
      emoji: '🥬',
      tempMin: 15, tempMax: 22,
      phMin: 6.0, phMax: 7.0,
      ecMin: 1.5, ecMax: 2.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Resh (2022), Hydroponic Food Production',
    ),
    PlantProfile(
      nombre: 'Berenjena',
      emoji: '🍆',
      tempMin: 22, tempMax: 32,
      phMin: 5.5, phMax: 6.5,
      ecMin: 2.5, ecMax: 3.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Resh (2022), Hydroponic Food Production',
    ),
    PlantProfile(
      nombre: 'Melón',
      emoji: '🍈',
      tempMin: 22, tempMax: 32,
      phMin: 5.5, phMax: 6.5,
      ecMin: 2.0, ecMax: 3.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Resh (2022), Hydroponic Food Production',
    ),
    PlantProfile(
      nombre: 'Brócoli',
      emoji: '🥦',
      tempMin: 15, tempMax: 22,
      phMin: 6.0, phMax: 7.0,
      ecMin: 2.5, ecMax: 3.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Resh (2022), Hydroponic Food Production',
    ),
    PlantProfile(
      nombre: 'Coliflor',
      emoji: '🥦',
      tempMin: 15, tempMax: 22,
      phMin: 6.0, phMax: 7.0,
      ecMin: 2.0, ecMax: 3.0,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Resh (2022), Hydroponic Food Production',
    ),
    PlantProfile(
      nombre: 'Habichuela / Judía Verde',
      emoji: '🫘',
      tempMin: 18, tempMax: 28,
      phMin: 5.5, phMax: 6.5,
      ecMin: 2.0, ecMax: 3.0,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'FAO; CORPOICA',
    ),

    // ═══════════════════════════════════════════════════════════════════
    // AROMÁTICAS Y HIERBAS
    // ═══════════════════════════════════════════════════════════════════
    PlantProfile(
      nombre: 'Albahaca',
      emoji: '🌿',
      tempMin: 15, tempMax: 24,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.0, ecMax: 1.6,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Rusu et al. (2021), Sustainability',
    ),
    PlantProfile(
      nombre: 'Cilantro',
      emoji: '🌿',
      tempMin: 15, tempMax: 25,
      phMin: 5.5, phMax: 6.7,
      ecMin: 1.0, ecMax: 1.8,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Resh (2022); FAO Manual hidroponía',
    ),
    PlantProfile(
      nombre: 'Perejil',
      emoji: '🌿',
      tempMin: 15, tempMax: 25,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.0, ecMax: 1.8,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Resh (2022), Hydroponic Food Production',
    ),
    PlantProfile(
      nombre: 'Menta',
      emoji: '🌿',
      tempMin: 15, tempMax: 25,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.0, ecMax: 1.6,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Resh (2022), Hydroponic Food Production',
    ),
    PlantProfile(
      nombre: 'Hierbabuena',
      emoji: '🌿',
      tempMin: 15, tempMax: 25,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.0, ecMax: 1.6,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Resh (2022); estimado similar a menta',
    ),
    PlantProfile(
      nombre: 'Tomillo',
      emoji: '🌿',
      tempMin: 15, tempMax: 25,
      phMin: 5.5, phMax: 7.0,
      ecMin: 0.8, ecMax: 1.6,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Resh (2022), Hydroponic Food Production',
    ),
    PlantProfile(
      nombre: 'Romero',
      emoji: '🌿',
      tempMin: 15, tempMax: 28,
      phMin: 5.5, phMax: 6.5,
      ecMin: 0.8, ecMax: 1.6,
      nivelAguaMin: 15, nivelFertilizanteMin: 15,
      fuente: 'Resh (2022), Hydroponic Food Production',
    ),
    PlantProfile(
      nombre: 'Orégano',
      emoji: '🌿',
      tempMin: 15, tempMax: 28,
      phMin: 5.5, phMax: 7.0,
      ecMin: 1.0, ecMax: 1.5,
      nivelAguaMin: 15, nivelFertilizanteMin: 15,
      fuente: 'Resh (2022); estimado aromáticas',
    ),
    PlantProfile(
      nombre: 'Cebollín / Ciboulette',
      emoji: '🌱',
      tempMin: 15, tempMax: 25,
      phMin: 6.0, phMax: 7.0,
      ecMin: 1.0, ecMax: 1.8,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Resh (2022), Hydroponic Food Production',
    ),
    PlantProfile(
      nombre: 'Stevia',
      emoji: '🍃',
      tempMin: 20, tempMax: 30,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.0, ecMax: 1.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Agrosavia Colombia; datos de campo',
    ),
    PlantProfile(
      nombre: 'Caléndula',
      emoji: '🌼',
      tempMin: 14, tempMax: 24,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.0, ecMax: 1.8,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'FAO; datos de cultivo ornamental',
    ),
    PlantProfile(
      nombre: 'Ruda',
      emoji: '🌿',
      tempMin: 15, tempMax: 28,
      phMin: 5.5, phMax: 7.0,
      ecMin: 0.8, ecMax: 1.5,
      nivelAguaMin: 15, nivelFertilizanteMin: 15,
      fuente: 'Agronet Colombia; tradicional',
    ),

    // ═══════════════════════════════════════════════════════════════════
    // ORNAMENTALES DE INTERIOR
    // ═══════════════════════════════════════════════════════════════════
    PlantProfile(
      nombre: 'Pothos / Epipremnum',
      emoji: '🌿',
      tempMin: 18, tempMax: 30,
      phMin: 5.5, phMax: 6.5,
      ecMin: 0.8, ecMax: 1.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Dantas et al. (2024); estimado',
    ),
    PlantProfile(
      nombre: 'Sansevieria',
      emoji: '🪴',
      tempMin: 15, tempMax: 28,
      phMin: 5.5, phMax: 6.5,
      ecMin: 0.5, ecMax: 1.2,
      nivelAguaMin: 15, nivelFertilizanteMin: 15,
      fuente: 'Dantas et al. (2024); estimado',
    ),
    PlantProfile(
      nombre: 'Espatifilo / Lirio de Paz',
      emoji: '🌱',
      tempMin: 18, tempMax: 26,
      phMin: 5.5, phMax: 6.5,
      ecMin: 0.8, ecMax: 1.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Dantas et al. (2024); Mercado-Sierra et al. (2022)',
    ),
    PlantProfile(
      nombre: 'Monstera Deliciosa',
      emoji: '🌿',
      tempMin: 18, tempMax: 28,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.0, ecMax: 1.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Estimado plantas aráceas tropicales',
    ),
    PlantProfile(
      nombre: 'Filodendro',
      emoji: '🌿',
      tempMin: 18, tempMax: 28,
      phMin: 5.5, phMax: 6.5,
      ecMin: 0.8, ecMax: 1.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Estimado plantas aráceas tropicales',
    ),
    PlantProfile(
      nombre: 'Calathea / Goeppertia',
      emoji: '🌿',
      tempMin: 18, tempMax: 26,
      phMin: 5.5, phMax: 6.5,
      ecMin: 0.5, ecMax: 1.2,
      nivelAguaMin: 25, nivelFertilizanteMin: 20,
      fuente: 'Estimado marantáceas tropicales',
    ),
    PlantProfile(
      nombre: 'Anturio',
      emoji: '🌺',
      tempMin: 20, tempMax: 28,
      phMin: 5.5, phMax: 6.5,
      ecMin: 0.8, ecMax: 1.5,
      nivelAguaMin: 25, nivelFertilizanteMin: 20,
      fuente: 'Asocolflores Colombia; estimado',
    ),
    PlantProfile(
      nombre: 'Orquídea Phalaenopsis',
      emoji: '🌸',
      tempMin: 18, tempMax: 28,
      phMin: 5.5, phMax: 6.5,
      ecMin: 0.5, ecMax: 1.0,
      nivelAguaMin: 15, nivelFertilizanteMin: 15,
      fuente: 'Asocolflores Colombia; hidroponía semi-abierta',
    ),
    PlantProfile(
      nombre: 'Helecho Boston',
      emoji: '🌿',
      tempMin: 16, tempMax: 26,
      phMin: 5.5, phMax: 6.5,
      ecMin: 0.8, ecMax: 1.5,
      nivelAguaMin: 25, nivelFertilizanteMin: 20,
      fuente: 'Estimado helechos tropicales',
    ),
    PlantProfile(
      nombre: 'Begonia',
      emoji: '🌺',
      tempMin: 16, tempMax: 24,
      phMin: 5.5, phMax: 6.5,
      ecMin: 0.8, ecMax: 1.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Asocolflores Colombia; estimado',
    ),
    PlantProfile(
      nombre: 'Drácena',
      emoji: '🪴',
      tempMin: 18, tempMax: 28,
      phMin: 6.0, phMax: 7.0,
      ecMin: 0.5, ecMax: 1.2,
      nivelAguaMin: 15, nivelFertilizanteMin: 15,
      fuente: 'Estimado plantas tropicales interior',
    ),
    PlantProfile(
      nombre: 'Ficus Elastica',
      emoji: '🌿',
      tempMin: 18, tempMax: 28,
      phMin: 5.5, phMax: 6.5,
      ecMin: 0.8, ecMax: 1.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Estimado moráceas tropicales',
    ),
    PlantProfile(
      nombre: 'Suculenta / Echeveria',
      emoji: '🪴',
      tempMin: 15, tempMax: 28,
      phMin: 5.5, phMax: 6.5,
      ecMin: 0.3, ecMax: 1.0,
      nivelAguaMin: 10, nivelFertilizanteMin: 10,
      fuente: 'Estimado suculentas',
    ),
    PlantProfile(
      nombre: 'Cactus / Opuntia',
      emoji: '🌵',
      tempMin: 18, tempMax: 35,
      phMin: 5.5, phMax: 7.0,
      ecMin: 0.3, ecMax: 1.0,
      nivelAguaMin: 10, nivelFertilizanteMin: 10,
      fuente: 'Estimado cactáceas',
    ),
    PlantProfile(
      nombre: 'Palma Areca',
      emoji: '🌴',
      tempMin: 18, tempMax: 28,
      phMin: 6.0, phMax: 7.0,
      ecMin: 0.8, ecMax: 1.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Estimado palmáceas ornamentales',
    ),
    PlantProfile(
      nombre: 'Croton',
      emoji: '🍂',
      tempMin: 18, tempMax: 30,
      phMin: 5.5, phMax: 6.5,
      ecMin: 0.8, ecMax: 1.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Estimado euforbiáceas ornamentales',
    ),

    // ═══════════════════════════════════════════════════════════════════
    // FLORES DE CORTE (INDUSTRIA COLOMBIANA)
    // ═══════════════════════════════════════════════════════════════════
    PlantProfile(
      nombre: 'Rosa',
      emoji: '🌹',
      tempMin: 15, tempMax: 25,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.5, ecMax: 2.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Asocolflores Colombia; Resh (2022)',
    ),
    PlantProfile(
      nombre: 'Clavel',
      emoji: '🌸',
      tempMin: 12, tempMax: 22,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.5, ecMax: 2.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Asocolflores Colombia',
    ),
    PlantProfile(
      nombre: 'Crisantemo',
      emoji: '🌼',
      tempMin: 15, tempMax: 25,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.5, ecMax: 2.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Asocolflores Colombia',
    ),
    PlantProfile(
      nombre: 'Hortensia',
      emoji: '💐',
      tempMin: 14, tempMax: 22,
      phMin: 5.0, phMax: 6.0,
      ecMin: 1.5, ecMax: 2.5,
      nivelAguaMin: 25, nivelFertilizanteMin: 20,
      fuente: 'Asocolflores Colombia; Antioquia',
    ),
    PlantProfile(
      nombre: 'Girasol',
      emoji: '🌻',
      tempMin: 18, tempMax: 28,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.2, ecMax: 2.0,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Datos de floricultura colombiana',
    ),
    PlantProfile(
      nombre: 'Gerbera',
      emoji: '🌼',
      tempMin: 18, tempMax: 25,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.5, ecMax: 2.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Asocolflores Colombia',
    ),
    PlantProfile(
      nombre: 'Astromelia',
      emoji: '🌸',
      tempMin: 13, tempMax: 22,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.5, ecMax: 2.5,
      nivelAguaMin: 20, nivelFertilizanteMin: 20,
      fuente: 'Asocolflores Colombia; Bogotá Sabana',
    ),
    PlantProfile(
      nombre: 'Heliconia',
      emoji: '🌺',
      tempMin: 22, tempMax: 32,
      phMin: 5.5, phMax: 6.5,
      ecMin: 1.0, ecMax: 2.0,
      nivelAguaMin: 25, nivelFertilizanteMin: 20,
      fuente: 'Flora tropical colombiana; estimado',
    ),
  ];

  // ═══════════════════════════════════════════════════════════════════════
  // CULTIVO EN TIERRA (soil-first — ROADMAP_PRODUCTO.md P1)
  // ═══════════════════════════════════════════════════════════════════════
  // Estas plantas se monitorean por humedad de suelo (%), no por EC/nivel de
  // tanque. Los rangos son de referencia horticultural general — NO provienen
  // de un estudio citado como los perfiles hidropónicos; deben validarse con
  // una fuente agronómica antes de producción.
  static const List<PlantProfile> plantasSuelo = [
    PlantProfile(
      nombre: 'Albahaca (tierra)',
      emoji: '🌿',
      tempMin: 18, tempMax: 30,
      phMin: 6.0, phMax: 7.5,
      ecMin: 0, ecMax: 0,
      nivelAguaMin: 0, nivelFertilizanteMin: 0,
      humedadSueloMin: 40, humedadSueloMax: 70,
      tipoCultivo: 'suelo',
      fuente: 'Rango general de referencia — validar con fuente agronómica',
    ),
    PlantProfile(
      nombre: 'Menta (tierra)',
      emoji: '🌱',
      tempMin: 15, tempMax: 28,
      phMin: 6.0, phMax: 7.0,
      ecMin: 0, ecMax: 0,
      nivelAguaMin: 0, nivelFertilizanteMin: 0,
      humedadSueloMin: 50, humedadSueloMax: 75,
      tipoCultivo: 'suelo',
      fuente: 'Rango general de referencia — validar con fuente agronómica',
    ),
    PlantProfile(
      nombre: 'Tomate (tierra)',
      emoji: '🍅',
      tempMin: 18, tempMax: 28,
      phMin: 6.0, phMax: 6.8,
      ecMin: 0, ecMax: 0,
      nivelAguaMin: 0, nivelFertilizanteMin: 0,
      humedadSueloMin: 45, humedadSueloMax: 70,
      tipoCultivo: 'suelo',
      fuente: 'Rango general de referencia — validar con fuente agronómica',
    ),
    PlantProfile(
      nombre: 'Fresa (tierra)',
      emoji: '🍓',
      tempMin: 15, tempMax: 26,
      phMin: 5.5, phMax: 6.8,
      ecMin: 0, ecMax: 0,
      nivelAguaMin: 0, nivelFertilizanteMin: 0,
      humedadSueloMin: 50, humedadSueloMax: 70,
      tipoCultivo: 'suelo',
      fuente: 'Rango general de referencia — validar con fuente agronómica',
    ),
    PlantProfile(
      nombre: 'Suculenta / Cactus',
      emoji: '🌵',
      tempMin: 18, tempMax: 32,
      phMin: 6.0, phMax: 7.5,
      ecMin: 0, ecMax: 0,
      nivelAguaMin: 0, nivelFertilizanteMin: 0,
      humedadSueloMin: 10, humedadSueloMax: 30,
      tipoCultivo: 'suelo',
      fuente: 'Rango general de referencia — validar con fuente agronómica',
    ),
  ];

  /// Todos los perfiles (hidropónicos + suelo). El selector filtra por
  /// [PlantProfile.tipoCultivo] según el dispositivo activo.
  static List<PlantProfile> get todas => [...plantas, ...plantasSuelo];
}
