// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these placeholder values with the real web app config.
  // Steps:
  //   1. Go to Firebase Console → Project hydrotrack-13047 → Project Settings
  //   2. Under "Your apps", click "Add app" → Web (</>) and register it
  //   3. Copy the firebaseConfig object and fill in the values below
  //   4. Or re-run: flutterfire configure --project=hydrotrack-13047
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: 'REPLACE_WITH_WEB_APP_ID',        // format: 1:495915712501:web:XXXXXXXX
    messagingSenderId: '495915712501',
    projectId: 'hydrotrack-13047',
    authDomain: 'hydrotrack-13047.firebaseapp.com',
    storageBucket: 'hydrotrack-13047.firebasestorage.app',
    databaseURL: 'https://hydrotrack-13047.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADO17mJSijQWZmYXcju-9tx1ftHD-HYRU',
    appId: '1:495915712501:android:bc93226d35c66ee2a9eabc',
    messagingSenderId: '495915712501',
    projectId: 'hydrotrack-13047',
    storageBucket: 'hydrotrack-13047.firebasestorage.app',
    databaseURL: 'https://hydrotrack-13047.firebaseio.com',
  );
}
